name: dash_app_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 # Usa Python 3.9, una versión estable para estas librerías
  - pandas=2.0.3 # Mantenemos la versión de pandas que probamos
  - numpy=1.26.4
  - plotly=5.22.0
  - dash=2.17.0
  - prophet=1.1.1
  - requests=2.31.0
  - openpyxl=3.1.2
  - gunicorn=22.0.0
  - matplotlib=3.8.4
  - lxml=5.4.0
  - pip
  - pip:
    - dash-bootstrap-components # Si lo usas, si no, puedes quitarlo